//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangaModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MangaSeedError
    {
        public int id { get; set; }
        public int MangaId { get; set; }
        public string Chapter { get; set; }
        public int Page { get; set; }
        public string ErrorDetails { get; set; }
        public string StackTrace { get; set; }
    }
}
