//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangaModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MangaSeed
    {
        public int C_id { get; set; }
        public int mangaid { get; set; }
        public string release { get; set; }
        public string time { get; set; }
        public string view { get; set; }
        public string name { get; set; }
        public Nullable<bool> end { get; set; }
        public Nullable<bool> @new { get; set; }
        public Nullable<bool> hot { get; set; }
        public Nullable<bool> update { get; set; }
        public Nullable<bool> vip { get; set; }
        public string img { get; set; }
    }
}
